image: node:8

variables:
  GIT_COMMITTER_NAME: stardust
  GIT_COMMITTER_EMAIL: stardust@ultimaker.com
  GIT_AUTHOR_NAME: stardust
  GIT_AUTHOR_EMAIL: stardust@ultimaker.com

stages:
  - test
  - deploy

before_script:
  - yarn install
  - echo "${SSH_PRIVATE_KEY}" | base64 -d > "${CI_PROJECT_DIR}/id_rsa"

test:
  stage: test
  script:
    - yarn lint
    - yarn test:coverage
    - yarn build
  except:
    - master

pages:
  stage: deploy
  script:
    - yarn build
  artifacts:
    paths:
    - public
  only:
    - master

publish:
  stage: deploy
  script:
    - npm version patch
    - GIT_SSH_COMMAND="ssh -i ${CI_PROJECT_DIR}/id_rsa" git push git@github.com:Ultimaker/react-web-components.git
    - npm publish
  only:
    - master
