image: node:8

stages:
  - test
  - deploy

before_script:
  - yarn install

test:
  stage: test
  script:
    - yarn lint
    - yarn test:coverage
    - yarn build
  except:
    - master

pages:
  stage: deploy
  script:
    - yarn build
  artifacts:
    paths:
    - public
  only:
    - master
