image: node:8

stages:
  - test
  - deploy

before_script:
  - yarn install

test:
  stage: test
  tags:
    - docker
    - kubernetes
  script:
    # TODO: run actual tests here when we have them, but for now we just build storybook to test
    - yarn build
  except:
    - master
    # for testing only
    - small-popup-fixes

pages:
  stage: deploy
  script:
    - yarn build
  artifacts:
    paths:
    - docs
  only:
    - master
    # for testing only
    - small-popup-fixes
