image: node:8

stages:
  - test
  - deploy

before_script:
  - npm install

test:
  stage: test
  script:
    - npm run lint
    - npm run test:coverage
    - npm run build
  except:
    - master

pages:
  stage: deploy
  script:
    - npm run build
  artifacts:
    paths:
    - public
  only:
    - master

publish:
  stage: deploy
  script:
    - npm run lint
    - npm run test:coverage
    - npm run build
    - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
    - npm --unsafe-perm publish
  only:
    - tags
