image: node:8

variables:
  GIT_COMMITTER_NAME: stardust
  GIT_COMMITTER_EMAIL: stardust@ultimaker.com
  GIT_AUTHOR_NAME: stardust
  GIT_AUTHOR_EMAIL: stardust@ultimaker.com

stages:
  - test
  - deploy

before_script:
  - npm install

test:
  stage: test
  script:
    - npm run lint
    - npm run lint:scss
    - npm run test:coverage
    - npm run build
  except:
    - master

pages:
  stage: deploy
  script:
    - npm run build
  artifacts:
    paths:
    - public
  only:
    - master

publish:
  stage: deploy
  script:
    - npm run build
    - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
    - npm --unsafe-perm publish
  only:
    - tags
