name: Build and test
on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache npm
      uses: actions/cache@v1
      with:
        path: /home/runner/.npm
        key: npm-cache-${{ hashFiles('**/package-lock.json') }}
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm ci
    - run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: /home/runner/.npm
        key: npm-cache-${{ hashFiles('**/package-lock.json') }}
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm ci
    - run: npm run lint
    - run: npm run test:coverage
