name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - run: npm run build
  test:
    runs-on: ubuntu-latest
    needs: build
    - run: npm run lint
    - run: npm run test:coverage
